config/routes.rb
Rails.application.routes.draw do

  resources  :xero_sessions

  devise_for :users

  resources :inventory

  root 'home#index'
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  default_scope { order('desks ASC') }

  scope :soma, -> { where(location: 'Soma') }
  scope :south_park, -> { where(location: 'South Park') }
  scope :berkeley, -> { where(location: 'Berkeley') }
  scope :palo_alto, -> { where(location: 'Palo Alto') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/xero_session.rb
class Inventory < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController

  include ActionView::Helpers::NumberHelper

  def index
    @inventory = Inventory.all
  end

  def new
    @inventory = Inventory.new
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def update
    @inventory = Inventory.find(params[:id])
    @inventory.assign_attributes(inventory_params)

    if @inventory.save
      redirect_to inventory_index_path
    else
      flash.now[:alert] = "Error saving. Please try again."
      render :edit
    end
  end

  def create
    @inventory = Inventory.new
    @inventory.assign_attributes(inventory_params)

    if @inventory.save
      flash[:notice] = "Office was saved."
      redirect_to @inventory
    else
      flash.now[:alert] = "There was an error saving the office. Please try again."
      render :new
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])

    if @inventory.destroy
      flash[:notice] = "Office has been deleted."
      redirect_to inventory_index_path
    else
      flash.now[:alert] = "Error deleting office. Please try again."
      render :destroy
    end
  end

  private
  def inventory_params
    params.require(:inventory).permit(:office, :desks, :company, :price, :actual, :location)
  end

  def shortage

  end
end

app/controllers/xero_sessions_controller.rb
class XeroSessionsController < ApplicationController
  def index
    @contacts = @client.Contact.all
  end

  def initialize
    @client = Xeroizer::PrivateApplication.new(Rails.application.secrets.xero_consumer_key, Rails.application.secrets.xero_consumer_secret, Rails.application.secrets.cert_path)
  end

  def show
    @contact = @client.Contact.find(params[:id])
    @invoices = @client.Invoice.all(:where => 'Contact.Name == @contact.name.ToString() && Type=="ACCREC" && AmountDue <> 0')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?

    content_tag :div, capture(&block), class: css_class
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
  def total_sp_value
    29285.00
  end

  def total_soma_value
    15915.00
  end

  def total_berkeley_value
    24250.00
  end

  def total_palo_alto_value
    21390.00
  end

  def total_sp_current_value
    @south_park = Inventory.south_park
    @south_park.sum(:price)
  end

  def total_soma_current_value
    @soma = Inventory.soma
    @soma.sum(:price)
  end

  def total_berkeley_current_value
    @berkeley = Inventory.berkeley
    @berkeley.sum(:price)
  end

  def total_palo_alto_current_value
    @palo_alto = Inventory.palo_alto
    @palo_alto.sum(:price)
  end

  private
  def percent_to_capacity(total_location_value, total_value)
    percent = 100 * total_location_value / total_value
    percent.ceil
  end

  def shortage (actual, price)
    @shortage = (actual - price)
    @shortage
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/xero_sessions_helper.rb
module XeroSessionsHelper
end

app/views/home/index.html.erb
<div class="page-header">
  <h1>Community Manager Application <br><small>All of the things needed for your daily tasks</small></h1>


</div>

<div>
  <h2><small>Quick Links</small></h2>
  <ul>
    <li>Welcome Letters</li>
    <li>Virtual Member Notification</li>
    <li>Supplies Inventory</li>
    <li>Daily Record</li>
    <li>Pro Rate Calculator</li>
  </ul>
</div>

app/views/inventory/_table.html.erb
<div>
  <table class="table table-striped">
    <th>Total Value</th>
    <th>Total Current Value</th>
    <th>% to Capacity</th>

    <tr>
      <td><%= number_to_currency(location_total_value(location)) %></td>
      <td><%= number_to_currency(total_location_current_value) %></td>
      <td><%= percent_to_capacity(total_location_current_value, total_location_value)%>% </td>
    </tr>
  </table>
</div>
<div>
  <table class="table table-striped">
    <th></th>
    <th>Office #</th>
    <th>Desks</th>
    <th>Company Name</th>
    <th>Current Price</th>
    <th>Shortage</th>

    <% @inventory.location.each do |launch_pad| %>
      <% if launch_pad%>
          <tr>
          <% if launch_pad.price == 0 %>
            <tr class="warning">
          <% end %>
              <td><%= link_to "Edit", edit_inventory_path(launch_pad) %></td>
              <td><%= launch_pad.office %></td>
              <td> LP<%= launch_pad.desks%></td>
              <td><%= launch_pad.company %></td>
              <td><%= number_to_currency(launch_pad.price) %></td>
              <td><%= number_to_currency(launch_pad.shortage) %></td>
            </tr>
      <% end %>
    <% end %>

  </table>
</div>

app/views/inventory/_table_berkeley.html.erb
<div>
  <table class="table table-striped">
    <th>Total Value</th>
    <th>Total Current Value</th>
    <th>% to Capacity</th>

    <tr>
      <td><%= number_to_currency(total_berkeley_value) %></td>
      <td><%= number_to_currency(total_berkeley_current_value) %></td>
      <td><%= percent_to_capacity(total_berkeley_current_value, total_berkeley_value)%>% </td>
    </tr>
  </table>
</div>

<div>
  <table class="table table-striped">
    <th></th>
    <th>Office #</th>
    <th>Desks</th>
    <th>Company Name</th>
    <th>Current Price</th>
    <th>Actual Price</th>
    <th>Shortage</th>

    <% @inventory.each do |launch_pad| %>
      <% if launch_pad.location == "Berkeley" %>
        <tr>
          <% if launch_pad.price == 0 %>
            <tr class="warning">
          <% end %>
              <td><%= link_to "Edit", edit_inventory_path(launch_pad) %> <%= link_to "Delete", launch_pad, method: :delete, data: {confirm: "Are you sure you want to delete this office?"} %></td>
              <td><%= launch_pad.office %></td>
              <td> LP <%= launch_pad.desks%></td>
              <td><%= launch_pad.company %></td>
              <td><%= number_to_currency(launch_pad.price) %></td>
              <td><%= number_to_currency(launch_pad.actual) %></td>

            </tr>
      <% end %>
    <% end %>

  </table>
</div>

app/views/inventory/_table_palo_alto.html.erb
<div>
  <table class="table table-striped">
    <th>Total Value</th>
    <th>Total Current Value</th>
    <th>% to Capacity</th>

    <tr>
      <td><%= number_to_currency(total_palo_alto_value) %></td>
      <td><%= number_to_currency(total_palo_alto_current_value) %></td>
      <td><%= percent_to_capacity(total_palo_alto_current_value, total_palo_alto_value)%>% </td>
    </tr>
  </table>
</div>

<div>
  <table class="table table-striped">
    <th></th>
    <th>Office #</th>
    <th>Desks</th>
    <th>Company Name</th>
    <th>Current Price</th>
    <th>Actual Price</th>
    <th>Shortage</th>

    <% @inventory.each do |launch_pad| %>
      <% if launch_pad.location == "Palo Alto" %>
        <tr>
          <% if launch_pad.price == 0 %>
            <tr class="warning">
          <% end %>
              <td><%= link_to "Edit", edit_inventory_path(launch_pad) %> <%= link_to "Delete", launch_pad, method: :delete, data: {confirm: "Are you sure you want to delete this office?"} %></td>
              <td><%= launch_pad.office %></td>
              <td> LP <%= launch_pad.desks%></td>
              <td><%= launch_pad.company %></td>
              <td><%= number_to_currency(launch_pad.price) %></td>
              <td><%= number_to_currency(launch_pad.actual) %></td>

            </tr>
      <% end %>
    <% end %>

  </table>
</div>

app/views/inventory/_table_soma.html.erb
<div>
  <table class="table table-striped">
    <th>Total Value</th>
    <th>Total Current Value</th>
    <th>% to Capacity</th>

    <tr>
      <td><%= number_to_currency(total_soma_value) %></td>
      <td><%= number_to_currency(total_soma_current_value) %></td>
      <td><%= percent_to_capacity(total_soma_current_value, total_soma_value)%>% </td>
    </tr>
  </table>
</div>

<div>
  <table class="table table-striped">
    <th></th>
    <th>Office #</th>
    <th>Desks</th>
    <th>Company Name</th>
    <th>Current Price</th>
    <th>Actual Price</th>
    <th>Shortage</th>

    <% @inventory.each do |launch_pad| %>
      <% if launch_pad.location == "Soma" %>
        <tr>
          <% if launch_pad.price == 0 %>
            <tr class="warning">
          <% end %>
              <td><%= link_to "Edit", edit_inventory_path(launch_pad) %> <%= link_to "Delete", launch_pad, method: :delete, data: {confirm: "Are you sure you want to delete this office?"} %></td>
              <td><%= launch_pad.office %></td>
              <td> LP <%= launch_pad.desks%></td>
              <td><%= launch_pad.company %></td>
              <td><%= number_to_currency(launch_pad.price) %></td>
              <td><%= number_to_currency(launch_pad.actual) %></td>

            </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/inventory/_table_sp.html.erb
<div>
  <table class="table table-striped">
    <th>Total Value</th>
    <th>Total Current Value</th>
    <th>% to Capacity</th>

    <tr>
      <td><%= number_to_currency(total_sp_value) %></td>
      <td><%= number_to_currency(total_sp_current_value) %></td>
      <td><%= percent_to_capacity(total_sp_current_value, total_sp_value)%>% </td>
    </tr>
  </table>
</div>

<div>
  <table class="table table-striped">
    <th></th>
    <th>Office #</th>
    <th>Desks</th>
    <th>Company Name</th>
    <th>Current Price</th>
    <th>Actual Price</th>
    <th>Shortage</th>

    <% @inventory.south_park.each do |launch_pad| %>
      <% if launch_pad%>
          <tr>
          <% if launch_pad.price == 0 %>
            <tr class="warning">
          <% end %>
              <td>
                <!-- <%= link_to "Add", new_inventory_path %> -->
                <%= link_to "Edit", edit_inventory_path(launch_pad) %>
                <%= link_to "Delete", launch_pad, method: :delete, data: {confirm: "Are you sure you want to delete this office?"} %>
              </td>
              <td><%= launch_pad.office %></td>
              <td> LP<%= launch_pad.desks%></td>
              <td><%= launch_pad.company %></td>
              <td><%= number_to_currency(launch_pad.price) %></td>
              <td><%= number_to_currency(launch_pad.actual) %></td>

            </tr>
      <% end %>
    <% end %>

  </table>
</div>

app/views/inventory/edit.html.erb
<h1>Edit Office</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @inventory do |f| %>
      <div class="form-group">
        <%= f.label :office %>
        <%= f.text_field :office, class: 'form-control', placeholder: "Enter Office Number" %>
      </div>

      <div class="form-group">
        <%= f.label :desks %>
        <%= f.text_field :desks, class: 'form-control', placeholder: "Enter Office Size" %>
      </div>

      <div class="form-group">
        <%= f.label :company %>
        <%= f.text_field :company, class: 'form-control', placeholder: "Enter Company" %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control', placeholder: "Enter Office Price" %>
      </div>

      <div class="form-group">
        <%= f.label :actual_price %>
        <%= f.text_field :actual, class: 'form-control', placeholder: "Enter Office Price" %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/inventory/index.html.erb
<h1>Main Inventory</h1>

<div class="container">
  <div class="row">
    <h2>SOUTH PARK</h2>
      <%= render partial: 'table_sp' %>
  </div>

  <div class="row">
    <h2>SOMA</h2>
      <%= render partial: 'table_soma'%>
  </div>

  <div class="row">
    <h2>BERKELEY</h2>
      <%= render partial: 'table_berkeley'%>
  </div>

  <div class="row">
    <h2>PALO ALTO</h2>
      <%= render partial: 'table_palo_alto'%>
  </div>

</div>

app/views/inventory/new.html.erb
<h1>Create Office</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @inventory do |f| %>
      <div class="form-group">
        <%= f.label :office %>
        <%= f.text_field :office, class: 'form-control', placeholder: "Enter Office Number" %>
      </div>

      <div class="form-group">
        <%= f.label :desks %>
        <%= f.text_field :desks, class: 'form-control', placeholder: "Enter Office Size" %>
      </div>

      <div class="form-group">
        <%= f.label :company %>
        <%= f.text_field :company, class: 'form-control', placeholder: "Enter Company" %>
      </div>

      <div class="form-group">
        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control', placeholder: "Enter Office Price" %>
      </div>

      <div class="form-group">
        <%= f.label :actual %>
        <%= f.text_field :actual, class: 'form-control', placeholder: "Enter Actual Office Price" %>
      </div>

      <div class="form-group">
        <%= f.label :location %>
        <%= f.text_field :location, class: 'form-control', placeholder: "Enter office location" %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/inventory/show.html.erb
<h1>Inventory#show</h1>
<p>Find me in app/views/inventory/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %> </li>
      <li><%= link_to "Main Inventory", inventory_index_path %></li>
      <li><%= link_to "Members", xero_sessions_path %></li>
        <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/xero_sessions/index.html.erb
<div class="container">
  <h1>Members</h1>
  <div class="row">
    <% @contacts.each do |member| %>
      <%=link_to member.name, xero_session_path(member.id) %> </br>
    <% end %>
  </div>
</div>

app/views/xero_sessions/show.html.erb
<div>
  <%= @contact.name %> </br>
  
</div>

<div class="container">
  <%= @invoices.first.total %>
</div>